spring.application.name: kafka-streams-playground

spring.cloud.stream:
  function:
    definition: reverse;uppercase
  bindings:
    reverse-in-0:
      destination: strings
    reverse-out-0:
      destination: strings-reverse
    uppercase-in-0:
      destination: strings-reverse
    uppercase-out-0:
      destination: strings-processed
